Map<String, dynamic> whereReview = {
  "where_review": [
    {
      "USER_ID": "user1@gmail.com",
      "REVIEW_CONTENT": "음식이 맛있어요!",
      "WHERE_LIKE": 10,
      "WHERE_ID": "1", // String으로 변환
      "WHERE_NAME": "맥도날드",
      "WHERE_LOCATE": "대한민국 서울 은평구",
      "WHERE_RATE": 4.8,
      "IMAGES": ["https://i.imgur.com/tV71llG.jpeg"],
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "USER_ID": "user2@gmail.com",
      "REVIEW_CONTENT": "편안하고 좋아요.",
      "WHERE_LIKE": 5,
      "WHERE_ID": "2", // String으로 변환
      "WHERE_NAME": "버거킹",
      "WHERE_LOCATE": "대한민국 서울 강남구",
      "WHERE_RATE": 4.5,
      "IMAGES": ["https://i.imgur.com/yqg4Ovc.jpeg"],
      "REASON_MENU": false,
      "REASON_MOOD": true,
      "REASON_SAFE": false,
      "REASON_SEAT": true,
      "REASON_TRANSPORT": false,
      "REASON_PARK": true,
      "REASON_LONG": false,
      "REASON_VIEW": true,
      "REASON_INTERACTION": false,
      "REASON_QUITE": true,
      "REASON_PHOTO": false,
      "REASON_WATCH": true,
    },
    {
      "USER_ID": "user3@gmail.com",
      "REVIEW_CONTENT": "분위기가 좋고 조용해요.",
      "WHERE_LIKE": 8,
      "WHERE_ID": "3", // String으로 변환
      "WHERE_NAME": "아웃백 스테이크하우스",
      "WHERE_LOCATE": "대한민국 서울 종로구",
      "WHERE_RATE": 4.2,
      "IMAGES": ["https://i.imgur.com/x8fZoYQ.jpeg"],
      "REASON_MENU": true,
      "REASON_MOOD": true,
      "REASON_SAFE": false,
      "REASON_SEAT": true,
      "REASON_TRANSPORT": false,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": true,
      "REASON_PHOTO": false,
      "REASON_WATCH": true,
    },
    {
      "USER_ID": "user4@gmail.com",
      "REVIEW_CONTENT": "커피가 맛있고 쾌적해요.",
      "WHERE_LIKE": 15,
      "WHERE_ID": "4", // String으로 변환
      "WHERE_NAME": "스타벅스",
      "WHERE_LOCATE": "대한민국 서울 마포구",
      "WHERE_RATE": 4.7,
      "IMAGES": ["https://i.imgur.com/Ta4T3Eo.jpeg"],
      "REASON_MENU": false,
      "REASON_MOOD": true,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": true,
      "REASON_INTERACTION": false,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "USER_ID": "user5@gmail.com",
      "REVIEW_CONTENT": "음식이 정말 맛있네요!",
      "WHERE_LIKE": 20,
      "WHERE_ID": "5", // String으로 변환
      "WHERE_NAME": "Vapiano",
      "WHERE_LOCATE": "대한민국 서울 강남구",
      "WHERE_RATE": 4.6,
      "IMAGES": ["https://i.imgur.com/XIq1UM0.jpeg"],
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": false,
      "REASON_SEAT": true,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": false,
      "REASON_VIEW": true,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": true,
    },
    {
      "USER_ID": "user6@gmail.com",
      "REVIEW_CONTENT": "분위기가 좋아요.",
      "WHERE_LIKE": 7,
      "WHERE_ID": "6", // String으로 변환
      "WHERE_NAME": "이자카야 타마",
      "WHERE_LOCATE": "대한민국 서울 마포구",
      "WHERE_RATE": 4.3,
      "IMAGES": ["https://i.imgur.com/1q2h3vC.jpeg"],
      "REASON_MENU": false,
      "REASON_MOOD": true,
      "REASON_SAFE": true,
      "REASON_SEAT": true,
      "REASON_TRANSPORT": false,
      "REASON_PARK": true,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": false,
      "REASON_QUITE": true,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "USER_ID": "user7@gmail.com",
      "REVIEW_CONTENT": "안전하고 편리해요.",
      "WHERE_LIKE": 9,
      "WHERE_ID": "7", // String으로 변환
      "WHERE_NAME": "술익는집",
      "WHERE_LOCATE": "대한민국 서울 종로구",
      "WHERE_RATE": 4.1,
      "IMAGES": ["https://i.imgur.com/3b6TqjS.jpeg"],
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": true,
      "REASON_INTERACTION": false,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "USER_ID": "user8@gmail.com",
      "REVIEW_CONTENT": "깔끔하고 좋아요.",
      "WHERE_LIKE": 12,
      "WHERE_ID": "8", // String으로 변환
      "WHERE_NAME": "옥토버페스트",
      "WHERE_LOCATE": "대한민국 서울 강남구",
      "WHERE_RATE": 4.5,
      "IMAGES": ["https://i.imgur.com/U3a1M9j.jpeg"],
      "REASON_MENU": false,
      "REASON_MOOD": true,
      "REASON_SAFE": false,
      "REASON_SEAT": true,
      "REASON_TRANSPORT": false,
      "REASON_PARK": true,
      "REASON_LONG": false,
      "REASON_VIEW": true,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "USER_ID": "user9@gmail.com",
      "REVIEW_CONTENT": "편하고 안전해요.",
      "WHERE_LIKE": 11,
      "WHERE_ID": "9", // String으로 변환
      "WHERE_NAME": "포차천국",
      "WHERE_LOCATE": "대한민국 서울 서대문구",
      "WHERE_RATE": 4.2,
      "IMAGES": ["https://i.imgur.com/fQv4qJ3.jpeg"],
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": true,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": false,
      "REASON_VIEW": true,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": false,
      "REASON_WATCH": true,
    },
    {
      "USER_ID": "user10@gmail.com",
      "REVIEW_CONTENT": "조용하고 편안해요.",
      "WHERE_LIKE": 6,
      "WHERE_ID": "10", // String으로 변환
      "WHERE_NAME": "술마루",
      "WHERE_LOCATE": "대한민국 서울 성북구",
      "WHERE_RATE": 4.4,
      "IMAGES": ["https://i.imgur.com/aIv2cPi.jpeg"],
      "REASON_MENU": false,
      "REASON_MOOD": true,
      "REASON_SAFE": false,
      "REASON_SEAT": true,
      "REASON_TRANSPORT": false,
      "REASON_PARK": true,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": false,
      "REASON_QUITE": true,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "USER_ID": "user11@gmail.com",
      "REVIEW_CONTENT": "활기찬 분위기 좋습니다.",
      "WHERE_LIKE": 13,
      "WHERE_ID": "11", // String으로 변환
      "WHERE_NAME": "롯데월드",
      "WHERE_LOCATE": "대한민국 서울 송파구",
      "WHERE_RATE": 4.9,
      "IMAGES": ["https://i.imgur.com/ZqT6GgF.jpeg"],
      "REASON_MENU": true,
      "REASON_MOOD": true,
      "REASON_SAFE": false,
      "REASON_SEAT": true,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": false,
      "REASON_VIEW": true,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": false,
      "REASON_WATCH": true,
    },
    {
      "USER_ID": "user12@gmail.com",
      "REVIEW_CONTENT": "안전하고 깨끗해요.",
      "WHERE_LIKE": 14,
      "WHERE_ID": "12", // String으로 변환
      "WHERE_NAME": "에버랜드",
      "WHERE_LOCATE": "대한민국 경기 용인시",
      "WHERE_RATE": 4.7,
      "IMAGES": ["https://i.imgur.com/fKQh3pv.jpeg"],
      "REASON_MENU": false,
      "REASON_MOOD": true,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": false,
      "REASON_PARK": true,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": true,
      "REASON_PHOTO": false,
      "REASON_WATCH": true,
    },
    {
      "USER_ID": "user13@gmail.com",
      "REVIEW_CONTENT": "조용하고 안전합니다.",
      "WHERE_LIKE": 4,
      "WHERE_ID": "13", // String으로 변환
      "WHERE_NAME": "서울랜드",
      "WHERE_LOCATE": "대한민국 경기 과천시",
      "WHERE_RATE": 4.4,
      "IMAGES": ["https://i.imgur.com/zQwEImc.jpeg"],
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": true,
      "REASON_TRANSPORT": false,
      "REASON_PARK": false,
      "REASON_LONG": false,
      "REASON_VIEW": true,
      "REASON_INTERACTION": false,
      "REASON_QUITE": true,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "USER_ID": "user14@gmail.com",
      "REVIEW_CONTENT": "음식이 맛있고 분위기가 좋아요.",
      "WHERE_LIKE": 16,
      "WHERE_ID": "14", // String으로 변환
      "WHERE_NAME": "신라호텔",
      "WHERE_LOCATE": "대한민국 서울 중구",
      "WHERE_RATE": 4.8,
      "IMAGES": ["https://i.imgur.com/QWvDnKT.jpeg"],
      "REASON_MENU": true,
      "REASON_MOOD": true,
      "REASON_SAFE": false,
      "REASON_SEAT": true,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": true,
    },
    {
      "USER_ID": "user15@gmail.com",
      "REVIEW_CONTENT": "편안하고 안전한 곳입니다.",
      "WHERE_LIKE": 18,
      "WHERE_ID": "15", // String으로 변환
      "WHERE_NAME": "롯데호텔",
      "WHERE_LOCATE": "대한민국 서울 중구",
      "WHERE_RATE": 4.9,
      "IMAGES": ["https://i.imgur.com/j9H74R5.jpeg"],
      "REASON_MENU": false,
      "REASON_MOOD": true,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": true,
      "REASON_INTERACTION": false,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    }
  ]
};
