Map<String, dynamic> overall = {
  "overall_top_8": [
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맥도날드",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/tV71llG.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "롯데리아",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/4LxTzs6.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맥도날드",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/RbMGvqH.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "롯데리아",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/dG4sD5E.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맥도날드",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/FjVI1Bl.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "롯데리아",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/qH4D4eX.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맥도날드",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/sWqYC6j.png",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "롯데리아",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/Di8bHfk.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    // ... up to 8 places overall
  ]
};

Map<String, dynamic> byType = {
  "play": [
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맘스터치",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/tV71llG.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "푸라닭",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/4LxTzs6.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맥도날드",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/RbMGvqH.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "BHC",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/dG4sD5E.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "홍콩반점",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/FjVI1Bl.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "와플대학",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/qH4D4eX.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "울집물회",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/sWqYC6j.png",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "정신나갈거같아",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/Di8bHfk.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
  ],
  "eat": [
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맘스터치",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/tV71llG.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "푸라닭",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/4LxTzs6.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맥도날드",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/RbMGvqH.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "BHC",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/dG4sD5E.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "홍콩반점",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/FjVI1Bl.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "와플대학",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/qH4D4eX.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "울집물회",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/sWqYC6j.png",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "정신나갈거같아",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/Di8bHfk.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
  ],
  "sleep": [
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맘스터치",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/tV71llG.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "푸라닭",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/4LxTzs6.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맥도날드",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/RbMGvqH.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "BHC",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/dG4sD5E.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "홍콩반점",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/FjVI1Bl.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "와플대학",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/qH4D4eX.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "울집물회",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/sWqYC6j.png",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "정신나갈거같아",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/Di8bHfk.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
  ],
  "drink": [
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맘스터치",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/tV71llG.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "푸라닭",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/4LxTzs6.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "맥도날드",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/RbMGvqH.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "BHC",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/dG4sD5E.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "홍콩반점",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/FjVI1Bl.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "와플대학",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/qH4D4eX.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 1,
      "WHERE_NAME": "울집물회",
      "WHERE_LOCATE": "서울",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/sWqYC6j.png",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
    {
      "WHERE_ID": 2,
      "WHERE_NAME": "정신나갈거같아",
      "WHERE_LOCATE": "부산",
      "WHERE_RATE": 4.8,
      "IMAGE": "https://i.imgur.com/Di8bHfk.jpeg",
      "REASON_MENU": true,
      "REASON_MOOD": false,
      "REASON_SAFE": true,
      "REASON_SEAT": false,
      "REASON_TRANSPORT": true,
      "REASON_PARK": false,
      "REASON_LONG": true,
      "REASON_VIEW": false,
      "REASON_INTERACTION": true,
      "REASON_QUITE": false,
      "REASON_PHOTO": true,
      "REASON_WATCH": false,
    },
  ]
};
