Map<String, dynamic> where = {
  "where": [
    {
      "WHERE_TYPE": "eat",
      "WHERE_ID": "1",
      "WHERE_NAME": "맥도날드",
      "WHERE_LOCATE": "서울 은평구",
      "REASON_MENU": 0,
      "REASON_MOOD": 0,
      "REASON_SAFE": 0,
      "REASON_SEAT": 0,
      "REASON_TRANSPORT": 0,
      "REASON_PARK": 0,
      "REASON_LONG": 4,
      "REASON_VIEW": 1,
      "REASON_INTERACTION": 3,
      "REASON_QUITE": 2,
      "REASON_PHOTO": 6,
      "REASON_WATCH": 8,
      "IMAGE": "https://i.imgur.com/tV71llG.jpeg",
      "WHERE_RATE": 4.8,
      "LATITUDE": 37.5985,
      "LONGITUDE": 126.9310,
      "SAVE": 12,
    },
    {
      "WHERE_TYPE": "eat",
      "WHERE_ID": "2",
      "WHERE_NAME": "버거킹",
      "WHERE_LOCATE": "서울 강남구",
      "REASON_MENU": 5,
      "REASON_MOOD": 2,
      "REASON_SAFE": 1,
      "REASON_SEAT": 3,
      "REASON_TRANSPORT": 4,
      "REASON_PARK": 0,
      "REASON_LONG": 3,
      "REASON_VIEW": 1,
      "REASON_INTERACTION": 4,
      "REASON_QUITE": 2,
      "REASON_PHOTO": 5,
      "REASON_WATCH": 6,
      "IMAGE": "https://i.imgur.com/yqg4Ovc.jpeg",
      "WHERE_RATE": 4.2,
      "LATITUDE": 37.5013,
      "LONGITUDE": 127.0396,
      "SAVE": 7,
    },
    {
      "WHERE_TYPE": "eat",
      "WHERE_ID": "3",
      "WHERE_NAME": "아웃백 스테이크하우스",
      "WHERE_LOCATE": "서울 종로구",
      "REASON_MENU": 6,
      "REASON_MOOD": 4,
      "REASON_SAFE": 5,
      "REASON_SEAT": 3,
      "REASON_TRANSPORT": 2,
      "REASON_PARK": 3,
      "REASON_LONG": 2,
      "REASON_VIEW": 5,
      "REASON_INTERACTION": 2,
      "REASON_QUITE": 4,
      "REASON_PHOTO": 7,
      "REASON_WATCH": 3,
      "IMAGE": "https://i.imgur.com/x8fZoYQ.jpeg",
      "WHERE_RATE": 4.5,
      "LATITUDE": 37.5704,
      "LONGITUDE": 126.9827,
      "SAVE": 15,
    },
    {
      "WHERE_TYPE": "eat",
      "WHERE_ID": "4",
      "WHERE_NAME": "스타벅스",
      "WHERE_LOCATE": "서울 마포구",
      "REASON_MENU": 7,
      "REASON_MOOD": 5,
      "REASON_SAFE": 4,
      "REASON_SEAT": 4,
      "REASON_TRANSPORT": 3,
      "REASON_PARK": 1,
      "REASON_LONG": 1,
      "REASON_VIEW": 4,
      "REASON_INTERACTION": 3,
      "REASON_QUITE": 5,
      "REASON_PHOTO": 8,
      "REASON_WATCH": 2,
      "IMAGE": "https://i.imgur.com/Ta4T3Eo.jpeg",
      "WHERE_RATE": 4.7,
      "LATITUDE": 37.5502,
      "LONGITUDE": 126.9216,
      "SAVE": 22,
    },
    {
      "WHERE_TYPE": "eat",
      "WHERE_ID": "5",
      "WHERE_NAME": "Vapiano",
      "WHERE_LOCATE": "서울 강남구",
      "REASON_MENU": 6,
      "REASON_MOOD": 4,
      "REASON_SAFE": 5,
      "REASON_SEAT": 3,
      "REASON_TRANSPORT": 4,
      "REASON_PARK": 2,
      "REASON_LONG": 1,
      "REASON_VIEW": 5,
      "REASON_INTERACTION": 3,
      "REASON_QUITE": 4,
      "REASON_PHOTO": 7,
      "REASON_WATCH": 4,
      "IMAGE": "https://i.imgur.com/XIq1UM0.jpeg",
      "WHERE_RATE": 4.4,
      "LATITUDE": 37.5090,
      "LONGITUDE": 127.0571,
      "SAVE": 8,
    },
    {
      "WHERE_TYPE": "drink",
      "WHERE_ID": "6",
      "WHERE_NAME": "이자카야 타마",
      "WHERE_LOCATE": "서울 마포구",
      "REASON_MENU": 8,
      "REASON_MOOD": 7,
      "REASON_SAFE": 6,
      "REASON_SEAT": 5,
      "REASON_TRANSPORT": 4,
      "REASON_PARK": 1,
      "REASON_LONG": 2,
      "REASON_VIEW": 3,
      "REASON_INTERACTION": 5,
      "REASON_QUITE": 4,
      "REASON_PHOTO": 6,
      "REASON_WATCH": 7,
      "IMAGE": "https://i.imgur.com/1q2h3vC.jpeg",
      "WHERE_RATE": 4.5,
      "LATITUDE": 37.5488,
      "LONGITUDE": 126.9132,
      "SAVE": 10,
    },
    {
      "WHERE_TYPE": "drink",
      "WHERE_ID": "7",
      "WHERE_NAME": "술익는집",
      "WHERE_LOCATE": "서울 종로구",
      "REASON_MENU": 7,
      "REASON_MOOD": 6,
      "REASON_SAFE": 5,
      "REASON_SEAT": 4,
      "REASON_TRANSPORT": 3,
      "REASON_PARK": 2,
      "REASON_LONG": 3,
      "REASON_VIEW": 4,
      "REASON_INTERACTION": 2,
      "REASON_QUITE": 5,
      "REASON_PHOTO": 7,
      "REASON_WATCH": 6,
      "IMAGE": "https://i.imgur.com/3b6TqjS.jpeg",
      "WHERE_RATE": 4.3,
      "LATITUDE": 37.5693,
      "LONGITUDE": 126.9895,
      "SAVE": 5,
    },
    {
      "WHERE_TYPE": "drink",
      "WHERE_ID": "8",
      "WHERE_NAME": "옥토버페스트",
      "WHERE_LOCATE": "서울 강남구",
      "REASON_MENU": 6,
      "REASON_MOOD": 5,
      "REASON_SAFE": 4,
      "REASON_SEAT": 3,
      "REASON_TRANSPORT": 4,
      "REASON_PARK": 2,
      "REASON_LONG": 2,
      "REASON_VIEW": 5,
      "REASON_INTERACTION": 3,
      "REASON_QUITE": 4,
      "REASON_PHOTO": 8,
      "REASON_WATCH": 3,
      "IMAGE": "https://i.imgur.com/U3a1M9j.jpeg",
      "WHERE_RATE": 4.6,
      "LATITUDE": 37.5013,
      "LONGITUDE": 127.0246,
      "SAVE": 14,
    },
    {
      "WHERE_TYPE": "drink",
      "WHERE_ID": "9",
      "WHERE_NAME": "포차천국",
      "WHERE_LOCATE": "서울 서대문구",
      "REASON_MENU": 5,
      "REASON_MOOD": 4,
      "REASON_SAFE": 3,
      "REASON_SEAT": 2,
      "REASON_TRANSPORT": 3,
      "REASON_PARK": 1,
      "REASON_LONG": 4,
      "REASON_VIEW": 2,
      "REASON_INTERACTION": 4,
      "REASON_QUITE": 3,
      "REASON_PHOTO": 6,
      "REASON_WATCH": 5,
      "IMAGE": "https://i.imgur.com/fQv4qJ3.jpeg",
      "WHERE_RATE": 4.1,
      "LATITUDE": 37.5613,
      "LONGITUDE": 126.9387,
      "SAVE": 9,
    },
    {
      "WHERE_TYPE": "drink",
      "WHERE_ID": "10",
      "WHERE_NAME": "술마루",
      "WHERE_LOCATE": "서울 성북구",
      "REASON_MENU": 7,
      "REASON_MOOD": 5,
      "REASON_SAFE": 4,
      "REASON_SEAT": 3,
      "REASON_TRANSPORT": 4,
      "REASON_PARK": 2,
      "REASON_LONG": 3,
      "REASON_VIEW": 1,
      "REASON_INTERACTION": 4,
      "REASON_QUITE": 2,
      "REASON_PHOTO": 5,
      "REASON_WATCH": 6,
      "IMAGE": "https://i.imgur.com/aIv2cPi.jpeg",
      "WHERE_RATE": 4.2,
      "LATITUDE": 37.5886,
      "LONGITUDE": 127.0041,
      "SAVE": 6,
    },
    {
      "WHERE_TYPE": "play",
      "WHERE_ID": "11",
      "WHERE_NAME": "롯데월드",
      "WHERE_LOCATE": "서울 송파구",
      "REASON_MENU": 8,
      "REASON_MOOD": 7,
      "REASON_SAFE": 6,
      "REASON_SEAT": 4,
      "REASON_TRANSPORT": 5,
      "REASON_PARK": 4,
      "REASON_LONG": 3,
      "REASON_VIEW": 8,
      "REASON_INTERACTION": 7,
      "REASON_QUITE": 1,
      "REASON_PHOTO": 9,
      "REASON_WATCH": 6,
      "IMAGE": "https://i.imgur.com/ZqT6GgF.jpeg",
      "WHERE_RATE": 4.9,
      "LATITUDE": 37.5110,
      "LONGITUDE": 127.0980,
      "SAVE": 18,
    },
    {
      "WHERE_TYPE": "play",
      "WHERE_ID": "12",
      "WHERE_NAME": "에버랜드",
      "WHERE_LOCATE": "경기 용인시",
      "REASON_MENU": 9,
      "REASON_MOOD": 8,
      "REASON_SAFE": 7,
      "REASON_SEAT": 5,
      "REASON_TRANSPORT": 6,
      "REASON_PARK": 5,
      "REASON_LONG": 4,
      "REASON_VIEW": 9,
      "REASON_INTERACTION": 6,
      "REASON_QUITE": 2,
      "REASON_PHOTO": 10,
      "REASON_WATCH": 7,
      "IMAGE": "https://i.imgur.com/fKQh3pv.jpeg",
      "WHERE_RATE": 4.8,
      "LATITUDE": 37.2946,
      "LONGITUDE": 127.2025,
      "SAVE": 20,
    },
    {
      "WHERE_TYPE": "play",
      "WHERE_ID": "13",
      "WHERE_NAME": "서울랜드",
      "WHERE_LOCATE": "경기 과천시",
      "REASON_MENU": 7,
      "REASON_MOOD": 6,
      "REASON_SAFE": 5,
      "REASON_SEAT": 3,
      "REASON_TRANSPORT": 4,
      "REASON_PARK": 3,
      "REASON_LONG": 2,
      "REASON_VIEW": 6,
      "REASON_INTERACTION": 5,
      "REASON_QUITE": 3,
      "REASON_PHOTO": 8,
      "REASON_WATCH": 4,
      "IMAGE": "https://i.imgur.com/zQwEImc.jpeg",
      "WHERE_RATE": 4.4,
      "LATITUDE": 37.4367,
      "LONGITUDE": 127.0107,
      "SAVE": 13,
    },
    {
      "WHERE_TYPE": "sleep",
      "WHERE_ID": "14",
      "WHERE_NAME": "신라호텔",
      "WHERE_LOCATE": "서울 중구",
      "REASON_MENU": 8,
      "REASON_MOOD": 9,
      "REASON_SAFE": 10,
      "REASON_SEAT": 6,
      "REASON_TRANSPORT": 5,
      "REASON_PARK": 4,
      "REASON_LONG": 3,
      "REASON_VIEW": 9,
      "REASON_INTERACTION": 4,
      "REASON_QUITE": 7,
      "REASON_PHOTO": 10,
      "REASON_WATCH": 8,
      "IMAGE": "https://i.imgur.com/QWvDnKT.jpeg",
      "WHERE_RATE": 4.9,
      "LATITUDE": 37.5563,
      "LONGITUDE": 126.9638,
      "SAVE": 21,
    },
    {
      "WHERE_TYPE": "sleep",
      "WHERE_ID": "15",
      "WHERE_NAME": "롯데호텔",
      "WHERE_LOCATE": "서울 중구",
      "REASON_MENU": 7,
      "REASON_MOOD": 8,
      "REASON_SAFE": 9,
      "REASON_SEAT": 5,
      "REASON_TRANSPORT": 6,
      "REASON_PARK": 3,
      "REASON_LONG": 4,
      "REASON_VIEW": 8,
      "REASON_INTERACTION": 5,
      "REASON_QUITE": 6,
      "REASON_PHOTO": 9,
      "REASON_WATCH": 7,
      "IMAGE": "https://i.imgur.com/j9H74R5.jpeg",
      "WHERE_RATE": 4.8,
      "LATITUDE": 37.5663,
      "LONGITUDE": 126.9827,
      "SAVE": 17,
    },
    {
      "WHERE_TYPE": "sleep",
      "WHERE_ID": "16",
      "WHERE_NAME": "코엑스 인터컨티넨탈 호텔",
      "WHERE_LOCATE": "서울 강남구",
      "REASON_MENU": 6,
      "REASON_MOOD": 7,
      "REASON_SAFE": 8,
      "REASON_SEAT": 5,
      "REASON_TRANSPORT": 4,
      "REASON_PARK": 3,
      "REASON_LONG": 2,
      "REASON_VIEW": 7,
      "REASON_INTERACTION": 4,
      "REASON_QUITE": 5,
      "REASON_PHOTO": 8,
      "REASON_WATCH": 6,
      "IMAGE": "https://i.imgur.com/YNwTQV2.jpeg",
      "WHERE_RATE": 4.7,
      "LATITUDE": 37.5088,
      "LONGITUDE": 127.0617,
      "SAVE": 11,
    },
    {
      "WHERE_TYPE": "sleep",
      "WHERE_ID": "17",
      "WHERE_NAME": "밀레니엄 힐튼 호텔",
      "WHERE_LOCATE": "서울 용산구",
      "REASON_MENU": 5,
      "REASON_MOOD": 6,
      "REASON_SAFE": 7,
      "REASON_SEAT": 4,
      "REASON_TRANSPORT": 3,
      "REASON_PARK": 2,
      "REASON_LONG": 3,
      "REASON_VIEW": 6,
      "REASON_INTERACTION": 3,
      "REASON_QUITE": 5,
      "REASON_PHOTO": 7,
      "REASON_WATCH": 4,
      "IMAGE": "https://i.imgur.com/PCzC6YH.jpeg",
      "WHERE_RATE": 4.5,
      "LATITUDE": 37.5547,
      "LONGITUDE": 126.9706,
      "SAVE": 9,
    },
    {
      "WHERE_TYPE": "sleep",
      "WHERE_ID": "18",
      "WHERE_NAME": "포시즌스 호텔 서울",
      "WHERE_LOCATE": "서울 종로구",
      "REASON_MENU": 6,
      "REASON_MOOD": 7,
      "REASON_SAFE": 8,
      "REASON_SEAT": 5,
      "REASON_TRANSPORT": 4,
      "REASON_PARK": 3,
      "REASON_LONG": 4,
      "REASON_VIEW": 7,
      "REASON_INTERACTION": 4,
      "REASON_QUITE": 5,
      "REASON_PHOTO": 9,
      "REASON_WATCH": 6,
      "IMAGE": "https://i.imgur.com/8YHU4Ee.jpeg",
      "WHERE_RATE": 4.7,
      "LATITUDE": 37.5733,
      "LONGITUDE": 126.9795,
      "SAVE": 19,
    },
  ]
};
