// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfnFnba5ybdqVKRB5LWsDJ4wmYkCWjlX0',
    appId: '1:288800266354:web:2547d0fe7bea9f85690aeb',
    messagingSenderId: '288800266354',
    projectId: 'nahollo-39acd',
    authDomain: 'nahollo-39acd.firebaseapp.com',
    storageBucket: 'nahollo-39acd.appspot.com',
    measurementId: 'G-F1Q1YCPQLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwMiCY4Q8xQ4Wsk1s_bhNhoWT5YjtA7ro',
    appId: '1:288800266354:android:b01c78e0e396c3b3690aeb',
    messagingSenderId: '288800266354',
    projectId: 'nahollo-39acd',
    storageBucket: 'nahollo-39acd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ_YgQE158NLZ3Ijp3xwb3NHkAQLalHvU',
    appId: '1:288800266354:ios:771b6c2a3ed0f9fc690aeb',
    messagingSenderId: '288800266354',
    projectId: 'nahollo-39acd',
    storageBucket: 'nahollo-39acd.appspot.com',
    iosBundleId: 'com.example.nahollo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ_YgQE158NLZ3Ijp3xwb3NHkAQLalHvU',
    appId: '1:288800266354:ios:771b6c2a3ed0f9fc690aeb',
    messagingSenderId: '288800266354',
    projectId: 'nahollo-39acd',
    storageBucket: 'nahollo-39acd.appspot.com',
    iosBundleId: 'com.example.nahollo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfnFnba5ybdqVKRB5LWsDJ4wmYkCWjlX0',
    appId: '1:288800266354:web:bf1fdcc212760885690aeb',
    messagingSenderId: '288800266354',
    projectId: 'nahollo-39acd',
    authDomain: 'nahollo-39acd.firebaseapp.com',
    storageBucket: 'nahollo-39acd.appspot.com',
    measurementId: 'G-J6EYHB8QSD',
  );
}
