-- 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS Naholo_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 데이터베이스 사용
USE Naholo_db;

-- 필요한 테이블 생성 (참조 없는 테이블들 먼저 생성)
CREATE TABLE IF NOT EXISTS `Where` (
    WHERE_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    WHERE_NAME VARCHAR(255) NOT NULL,
    WHERE_LOCATE VARCHAR(255) NOT NULL,
    WHERE_RATE FLOAT NOT NULL,
    WHERE_TYPE VARCHAR(255) NOT NULL,
    PRIMARY KEY (WHERE_ID)
);

CREATE TABLE IF NOT EXISTS Users (
    ID VARCHAR(100) NOT NULL,
    PW VARCHAR(255) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    BIRTH DATE NOT NULL,
    GENDER TINYINT NOT NULL,
    NICKNAME VARCHAR(100) NOT NULL,
    USER_CHARACTER VARCHAR(100) NOT NULL,
    LV BIGINT NOT NULL DEFAULT 0,
    INTRODUCE VARCHAR(255) NOT NULL DEFAULT 'input',
    IMAGE BIGINT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Users_Image (
    ID VARCHAR(100) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Journal_image (
    IMAGE_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    JOURNAL_ID BIGINT NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    PRIMARY KEY (IMAGE_ID)
);

CREATE TABLE IF NOT EXISTS Journal_comment (
    COMMENT_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    POST_ID BIGINT NOT NULL,
    COMMENT_CONTENT VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    PRIMARY KEY (COMMENT_ID)
);

-- 외래 키가 필요한 테이블들 생성
CREATE TABLE IF NOT EXISTS WHERE_REVIEW (
    REVIEW_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(100) NOT NULL,
    WHERE_ID BIGINT UNSIGNED NOT NULL,
    REVIEW_CONTENT TEXT NOT NULL,
    WHERE_LIKE BIGINT NOT NULL,
    WHERE_RATE FLOAT NOT NULL,
    PRIMARY KEY (REVIEW_ID)
);

CREATE TABLE IF NOT EXISTS REVIEW_IMAGE (
    IMAGE_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    REVIEW_ID BIGINT UNSIGNED NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    PRIMARY KEY (IMAGE_ID),
    FOREIGN KEY (REVIEW_ID) REFERENCES WHERE_REVIEW(REVIEW_ID)
);

CREATE TABLE IF NOT EXISTS WHERE_IMAGE (
    IMAGE_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    WHERE_ID BIGINT UNSIGNED NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    PRIMARY KEY (IMAGE_ID),
    FOREIGN KEY (WHERE_ID) REFERENCES `Where`(WHERE_ID)
);

CREATE TABLE IF NOT EXISTS LIKES (
    LIKES_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(100) NOT NULL,
    WHERE_ID BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (LIKES_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(ID),
    FOREIGN KEY (WHERE_ID) REFERENCES `Where`(WHERE_ID)
);

CREATE TABLE IF NOT EXISTS Follow (
    ID VARCHAR(100) NOT NULL,
    FOLLOWER VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID, FOLLOWER),
    FOREIGN KEY (ID) REFERENCES Users(ID),
    FOREIGN KEY (FOLLOWER) REFERENCES Users(ID)
);

-- 외래 키 설정 추가
ALTER TABLE Journal_comment
ADD FOREIGN KEY (USER_ID) REFERENCES Users(ID);

ALTER TABLE WHERE_REVIEW
ADD FOREIGN KEY (USER_ID) REFERENCES Users(ID),
ADD FOREIGN KEY (WHERE_ID) REFERENCES `Where`(WHERE_ID);
